sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t skudzelia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true skudzelia/react-test npm test

after_success:
  - docker build -t skudzelia/multi-client ./client
  - docker build -t skudzelia/multi-nginx ./nginx
  - docker build -t skudzelia/multi-server ./server
  - docker build -t skudzelia/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push skudzelia/multi-client
  - docker push skudzelia/multi-nginx
  - docker push skudzelia/multi-server
  - docker push skudzelia/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-west-2-974526826878
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY